name: hacking-bridge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - pillow
    - opencv-python
    - fer
    - pandas
    - numpy
    - matplotlib
    - transformers
    - torch
    - deep-translator
    - tensorflow
    - tf-keras
