import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import argparse
import sys

def main():
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(description="Generate a clinical evaluation dashboard for emotion data.")
    parser.add_argument("csv_file", help="Path to the CSV file generated by the FER emotion logger.")
    args = parser.parse_args()

    print(f"Loading clinical data from {args.csv_file}...")
    try:
        df = pd.read_csv(args.csv_file)
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

    # Convert TimeStamp to datetime objects (Updated header)
    df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])

    # Define a fixed logical order for the Y-axis
    emotion_order = ['angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']
    # Updated header: Emocion
    df['Emocion'] = pd.Categorical(df['Emocion'], categories=emotion_order, ordered=True)

    # Extract the User ID for the title (defaults to 'Desconocido' if empty)
    usuario_id = df['Usuario'].iloc[0] if not df.empty else "Desconocido"

    # --- CREATE THE CLINICAL DASHBOARD ---
    # We create a figure with 2 subplots that share the exact same X-axis (Time)
    fig, (ax1, ax2) = plt.subplots(
        nrows=2, 
        ncols=1, 
        figsize=(14, 8), 
        sharex=True, 
        gridspec_kw={'height_ratios': [2, 1]} # The top graph gets more vertical space
    )

    # Added the Usuario ID to the main title and translated to Spanish
    fig.suptitle(f'Panel de Verificación Clínica de Emociones - Usuario: {usuario_id}', fontsize=16, fontweight='bold', y=0.95)

    # --- TOP PLOT: Emotion Timeline ---
    # We use a scatter plot, but color-coded by the emotion itself for clinical clarity
    colors = {'angry': 'red', 'disgust': 'saddlebrown', 'fear': 'purple', 
              'sad': 'blue', 'neutral': 'gray', 'surprise': 'orange', 'happy': 'green'}
    
    # Map the colors to the dataframe (Updated header)
    df['Color'] = df['Emocion'].map(colors)

    # Scatter plot using the new headers
    ax1.scatter(df['TimeStamp'], df['Emocion'], c=df['Color'], alpha=0.7, s=40)
    ax1.set_ylabel('Emoción Dominante', fontsize=12, fontweight='bold')
    ax1.grid(True, axis='y', linestyle='--', alpha=0.5)
    ax1.set_title('Línea de Tiempo del Estado Emocional', loc='left', fontsize=12)

    # --- BOTTOM PLOT: Confidence Score Tracker ---
    # Area chart using the new Confianza_en_prediccion header
    ax2.plot(df['TimeStamp'], df['Confianza_en_prediccion'], color='black', linewidth=1)
    ax2.fill_between(df['TimeStamp'], df['Confianza_en_prediccion'], 0, color='lightgray', alpha=0.5)
    
    ax2.set_ylabel('Confianza del Modelo', fontsize=12, fontweight='bold')
    ax2.set_xlabel('Tiempo de Sesión (HH:MM:SS)', fontsize=12)
    ax2.set_ylim(0, 1.05) # Keep the Y-axis strictly between 0 and 100%
    ax2.grid(True, axis='y', linestyle='--', alpha=0.5)
    ax2.set_title('Certeza de Predicción (0.0 a 1.0)', loc='left', fontsize=12)

    # Add a clinical "low confidence" warning line at 0.5 (50%)
    ax2.axhline(y=0.5, color='red', linestyle=':', label='Umbral del 50%')
    ax2.legend(loc='lower right')

    # --- FORMATTING ---
    # Format the X-axis for clean time reading
    ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
    fig.autofmt_xdate()

    plt.tight_layout()
    plt.subplots_adjust(top=0.88) # Adjust spacing so the title isn't cut off
    
    print("Dashboard generated successfully.")
    plt.show()

if __name__ == "__main__":
    main()