import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
import sys

def main():
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(description="Plot real-time emotion data from a CSV log.")
    parser.add_argument("csv_file", help="Path to the CSV file generated by the FER emotion logger.")
    args = parser.parse_args()

    # Load the CSV data
    print(f"Loading data from {args.csv_file}...")
    try:
        df = pd.read_csv(args.csv_file)
    except FileNotFoundError:
        print(f"Error: Could not find the file '{args.csv_file}'. Please check the path.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

    # Verify the CSV has the new expected columns
    expected_columns = ["Usuario", "TimeStamp", "Emocion", "Confianza_en_prediccion"]
    if not all(col in df.columns for col in expected_columns):
        print(f"Error: The CSV must contain the following columns: {expected_columns}")
        sys.exit(1)

    # Convert the TimeStamp column to actual datetime objects
    df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])

    # --- SPACETIME FIX ---
    # Sort by time and use a sequential index to remove visual gaps between sessions
    df = df.sort_values('TimeStamp').reset_index(drop=True)
    x_sequence = df.index
    # ---------------------

    # Extract user ID
    usuario_id = df['Usuario'].iloc[0] if not df.empty else "Desconocido"

    # Define a fixed logical order for the Y-axis so the graph is always consistent
    emotion_order = ['angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']
    
    # Convert the emotion column to a categorical type enforcing our order
    df['Emocion'] = pd.Categorical(
        df['Emocion'], 
        categories=emotion_order, 
        ordered=True
    )

    # Initialize the plot canvas
    plt.figure(figsize=(12, 6))

    # Create a scatter plot
    # X = Sequence, Y = Emocion, Color = Confianza_en_prediccion
    scatter = plt.scatter(
        x_sequence, 
        df['Emocion'], 
        c=df['Confianza_en_prediccion'], 
        cmap='viridis', # A color map ranging from purple (low) to yellow (high)
        alpha=0.8, 
        s=60 # Size of the dots
    )

    # Format the graph's appearance
    plt.title(f'Línea de Tiempo de Emociones - Usuario: {usuario_id}', fontsize=16, pad=15)
    plt.xlabel('Tiempo de Sesión', fontsize=12)
    plt.ylabel('Emoción Detectada', fontsize=12)

    # --- CUSTOM X-AXIS LABELS ---
    # Evenly distribute max 10 time labels across the sequence to prevent overlap
    num_ticks = min(10, len(df))
    if num_ticks > 0:
        tick_positions = np.linspace(0, len(df) - 1, num_ticks, dtype=int)
        tick_labels = df['TimeStamp'].iloc[tick_positions].dt.strftime('%H:%M:%S')
        
        plt.xticks(tick_positions, tick_labels)

    plt.gcf().autofmt_xdate() # Rotates the dates slightly so they don't overlap

    # Add a colorbar to explain the confidence score colors
    cbar = plt.colorbar(scatter)
    cbar.set_label('Confianza del Modelo (0.0 a 1.0)', rotation=270, labelpad=20)

    # Add horizontal grid lines to make tracking emotions easier
    plt.grid(True, axis='y', linestyle='--', alpha=0.6)
    
    # Adjust layout and render
    plt.tight_layout()
    print("Generating plot...")
    plt.show()

if __name__ == "__main__":
    main()