import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import argparse
import sys

def main():
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(description="Plot real-time emotion data from a CSV log.")
    parser.add_argument("csv_file", help="Path to the CSV file generated by the FER emotion logger.")
    args = parser.parse_args()

    # Load the CSV data
    print(f"Loading data from {args.csv_file}...")
    try:
        df = pd.read_csv(args.csv_file)
    except FileNotFoundError:
        print(f"Error: Could not find the file '{args.csv_file}'. Please check the path.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

    # Verify the CSV has the expected columns
    expected_columns = ["Timestamp", "Dominant_Emotion", "Confidence_Score"]
    if not all(col in df.columns for col in expected_columns):
        print(f"Error: The CSV must contain the following columns: {expected_columns}")
        sys.exit(1)

    # Convert the Timestamp column to actual datetime objects
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])

    # Define a fixed logical order for the Y-axis so the graph is always consistent
    emotion_order = ['angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']
    
    # Convert the emotion column to a categorical type enforcing our order
    df['Dominant_Emotion'] = pd.Categorical(
        df['Dominant_Emotion'], 
        categories=emotion_order, 
        ordered=True
    )

    # Initialize the plot canvas
    plt.figure(figsize=(12, 6))

    # Create a scatter plot
    # X = Time, Y = Emotion, Color = Confidence Score
    scatter = plt.scatter(
        df['Timestamp'], 
        df['Dominant_Emotion'], 
        c=df['Confidence_Score'], 
        cmap='viridis', # A color map ranging from purple (low) to yellow (high)
        alpha=0.8, 
        s=60 # Size of the dots
    )

    # Format the graph's appearance
    plt.title('Facial Emotion Timeline', fontsize=16, pad=15)
    plt.xlabel('Time', fontsize=12)
    plt.ylabel('Detected Emotion', fontsize=12)

    # Format the X-axis to display timestamps cleanly (Hours:Minutes:Seconds)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
    plt.gcf().autofmt_xdate() # Rotates the dates slightly so they don't overlap

    # Add a colorbar to explain the confidence score colors
    cbar = plt.colorbar(scatter)
    cbar.set_label('Model Confidence Score (0.0 to 1.0)', rotation=270, labelpad=20)

    # Add horizontal grid lines to make tracking emotions easier
    plt.grid(True, axis='y', linestyle='--', alpha=0.6)
    
    # Adjust layout and render
    plt.tight_layout()
    print("Generating plot...")
    plt.show()

if __name__ == "__main__":
    main()