import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
import sys

def main():
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(description="Generate a clinical evaluation dashboard for emotion data.")
    parser.add_argument("csv_file", help="Path to the CSV file generated by the FER emotion logger.")
    args = parser.parse_args()

    print(f"Loading clinical data from {args.csv_file}...")
    try:
        df = pd.read_csv(args.csv_file)
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

    # Convert TimeStamp to datetime objects
    df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])
    
    # Sort the dataframe by time and reset the index. 
    df = df.sort_values('TimeStamp').reset_index(drop=True)

    # Define a fixed logical order for the Y-axis
    emotion_order = ['angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']
    df['Emocion'] = pd.Categorical(df['Emocion'], categories=emotion_order, ordered=True)

    # Extract the User ID for the title
    usuario_id = df['Usuario'].iloc[0] if not df.empty else "Desconocido"

    # --- NEW: VISUAL STYLING ENGINE ---
    # Apply a dark background theme globally
    plt.style.use('dark_background')

    fig, (ax1, ax2) = plt.subplots(
        nrows=2, 
        ncols=1, 
        figsize=(14, 8), 
        sharex=True, 
        gridspec_kw={'height_ratios': [2, 1]} 
    )

    # Set background colors for the specific axes to a softer dark gray (not pure black)
    ax1.set_facecolor('#1e1e2e')
    ax2.set_facecolor('#1e1e2e')
    fig.patch.set_facecolor('#11111b')

    fig.suptitle(f'Panel de Verificación Clínica de Emociones - Usuario: {usuario_id}', 
                 fontsize=18, fontweight='bold', color='#cdd6f4', y=0.96)

    # Updated Color Palette: Modern, vibrant pastel/neon colors that pop on dark backgrounds
    colors = {
        'angry': '#f38ba8',     # Soft Red
        'disgust': '#fab387',   # Peach/Orange
        'fear': '#cba6f7',      # Lavender/Purple
        'sad': '#89b4fa',       # Bright Blue
        'neutral': '#a6adc8',   # Cool Gray
        'surprise': '#f9e2af',  # Yellow
        'happy': '#a6e3a1'      # Mint Green
    }
    df['Color'] = df['Emocion'].map(colors)

    x_sequence = df.index

    # --- TOP PLOT: Emotion Timeline ---
    # Increased dot size (s=80), added white borders (edgecolors) for a polished "bubble" look
    ax1.scatter(x_sequence, df['Emocion'], c=df['Color'], alpha=0.9, s=80, edgecolors='#1e1e2e', linewidth=1.5)
    ax1.set_ylabel('Emoción Dominante', fontsize=13, fontweight='bold', color='#bac2de')
    ax1.grid(True, axis='y', linestyle='-', color='#313244', alpha=0.7)
    ax1.set_title('Línea de Tiempo del Estado Emocional', loc='left', fontsize=14, color='#cdd6f4', pad=10)

    # --- BOTTOM PLOT: Confidence Score Tracker ---
    # Swapped harsh black for a glowing Cyan ('#89dceb')
    ax2.plot(x_sequence, df['Confianza_en_prediccion'], color='#89dceb', linewidth=2)
    ax2.fill_between(x_sequence, df['Confianza_en_prediccion'], 0, color='#89dceb', alpha=0.15)
    
    ax2.set_ylabel('Confianza del Modelo', fontsize=13, fontweight='bold', color='#bac2de')
    ax2.set_xlabel('Tiempo de Sesión', fontsize=13, color='#bac2de')
    ax2.set_ylim(0, 1.05) 
    ax2.grid(True, axis='y', linestyle='-', color='#313244', alpha=0.7)
    ax2.set_title('Certeza de Predicción (0.0 a 1.0)', loc='left', fontsize=14, color='#cdd6f4', pad=10)
    
    # Bright red dashed line for the threshold
    ax2.axhline(y=0.5, color='#f38ba8', linestyle='--', linewidth=1.5, label='Umbral del 50%')
    
    # Style the legend to match the dark theme
    legend = ax2.legend(loc='lower right', facecolor='#1e1e2e', edgecolor='#313244', labelcolor='#bac2de')

    # --- FORMATTING: Decluttering and Labels ---
    # Remove the heavy box around the graphs (spines) for a cleaner UI
    for ax in [ax1, ax2]:
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['left'].set_color('#45475a')
        ax.spines['bottom'].set_color('#45475a')
        ax.tick_params(colors='#bac2de')

    num_ticks = min(10, len(df))
    if num_ticks > 0:
        tick_positions = np.linspace(0, len(df) - 1, num_ticks, dtype=int)
        tick_labels = df['TimeStamp'].iloc[tick_positions].dt.strftime('%H:%M:%S')
        
        ax2.set_xticks(tick_positions)
        ax2.set_xticklabels(tick_labels)

    fig.autofmt_xdate(rotation=30) # Softer rotation angle for the text

    plt.tight_layout()
    plt.subplots_adjust(top=0.88, hspace=0.3) # Added hspace to let the graphs breathe
    
    print("Dashboard generated successfully.")
    plt.show()

if __name__ == "__main__":
    main()