import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import argparse
import sys
import warnings

# Suppress minor matplotlib warnings
warnings.filterwarnings("ignore")

def main():
    parser = argparse.ArgumentParser(description="Generate a professional dashboard for emotion data.")
    parser.add_argument("csv_file", help="Path to the CSV file generated by the FER emotion logger.")
    args = parser.parse_args()

    print(f"Loading data from {args.csv_file}...")
    try:
        df = pd.read_csv(args.csv_file)
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

    # --- DATA PREPARATION ---
    emotions = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral']
    
    if not all(col in df.columns for col in emotions + ["TimeStamp", "Dominant_Emotion"]):
        print("Error: CSV format mismatch. Ensure you are using the 10-column version of the logger.")
        sys.exit(1)

    df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])
    df = df.sort_values('TimeStamp').reset_index(drop=True)
    
    # Normalize the emotion probabilities
    df[emotions] = df[emotions].div(df[emotions].sum(axis=1), axis=0).fillna(0)

    # Calculate overall stats
    emotion_counts = df['Dominant_Emotion'].value_counts()
    
    for e in emotions:
        if e not in emotion_counts:
            emotion_counts[e] = 0
            
    emotion_counts = emotion_counts.sort_values(ascending=False)
    donut_counts = emotion_counts[emotion_counts > 0]

    # --- UI & THEME SETUP ---
    plt.style.use('dark_background')
    
    color_map = {
        'angry': '#ff0055',      
        'disgust': '#00ff00',    
        'fear': '#aa00ff',       
        'happy': '#ffcc00',      
        'sad': '#0088ff',        
        'surprise': '#00ffff',   
        'neutral': '#808080'     
    }
    
    bg_color = '#121212'
    panel_color = '#1e1e1e'
    text_color = '#e0e0e0'

    fig = plt.figure(figsize=(16, 9))
    fig.patch.set_facecolor(bg_color)
    
    # --- FIX 1: Dialed back height_ratios to [1, 1.8] for a balanced layout ---
    gs = GridSpec(2, 2, height_ratios=[1, 1.8], hspace=0.5)

    # --- TOP LEFT: DONUT CHART ---
    ax_pie = fig.add_subplot(gs[0, 0])
    ax_pie.set_facecolor(panel_color)
    
    pie_colors = [color_map[e] for e in donut_counts.index]
    
    wedges = ax_pie.pie(
        donut_counts.values, 
        startangle=90, 
        colors=pie_colors,
        wedgeprops=dict(width=0.4, edgecolor=bg_color, linewidth=2)
    )
    ax_pie.set_title("Proporción de Emociones (Global)", color=text_color, fontsize=14, fontweight='bold', pad=15)

    # --- TOP RIGHT: BAR CHART ---
    ax_bar = fig.add_subplot(gs[0, 1])
    ax_bar.set_facecolor(panel_color)
    
    bar_colors = [color_map[e] for e in emotion_counts.index]
    bars = ax_bar.bar(emotion_counts.index, emotion_counts.values, color=bar_colors, width=0.6)
    
    ax_bar.bar_label(bars, padding=3, color=text_color, fontweight='bold')
    
    ax_bar.set_title("Conteo de Fotogramas por Emoción", color=text_color, fontsize=14, fontweight='bold', pad=15)
    ax_bar.tick_params(colors=text_color)
    ax_bar.grid(axis='y', linestyle='--', alpha=0.2)

    # --- BOTTOM: 100% STACKED AREA CHART (TIMELINE) ---
    ax_line = fig.add_subplot(gs[1, :])
    ax_line.set_facecolor(panel_color)
    
    x_sequence = df.index
    stack_data = [df[e] for e in emotions]
    stack_colors = [color_map[e] for e in emotions]
    
    ax_line.stackplot(x_sequence, stack_data, labels=emotions, colors=stack_colors, alpha=0.9)
    
    ax_line.set_title("Línea de Tiempo (Distribución de Probabilidad)", color=text_color, fontsize=14, fontweight='bold', loc='left', pad=30)
    ax_line.set_ylim(0, 1)
    ax_line.set_xlim(x_sequence.min(), x_sequence.max())
    
    ax_line.set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    ax_line.set_yticklabels(['0%', '20%', '40%', '60%', '80%', '100%'])
    ax_line.tick_params(colors=text_color)
    
    num_ticks = min(12, len(df))
    if num_ticks > 0:
        tick_positions = np.linspace(0, len(df) - 1, num_ticks, dtype=int)
        tick_labels = df['TimeStamp'].iloc[tick_positions].dt.strftime('%H:%M:%S')
        ax_line.set_xticks(tick_positions)
        ax_line.set_xticklabels(tick_labels)

    # --- BIG VERTICAL LEGEND ON THE LEFT ---
    legend_handles = [mpatches.Patch(color=color_map[e], label=e.upper()) for e in emotions]
    
    # --- FIX 2: Lowered the Y-anchor to 0.80 to match the new top row height ---
    fig.legend(handles=legend_handles, loc='center left', bbox_to_anchor=(0.02, 0.80), 
               prop={'size': 14, 'weight': 'bold'}, frameon=False, labelcolor=text_color)

    # Clean up borders (spines) for all plots
    for ax in [ax_pie, ax_bar, ax_line]:
        for spine in ax.spines.values():
            spine.set_color('#333333')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    # --- FORMATTING ADJUSTMENT ---
    plt.tight_layout(rect=[0.15, 0, 1, 1])
    
    print("Dashboard generated successfully.")
    plt.show()

if __name__ == "__main__":
    main()